# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3c5c1db22f997339312482fa29feb09d7e790d17009b25416f26802ff32366bf27428edd65c4c24d5c3edc5a64aaeea0bdcfe58ae4b2b72c8eb196109c88b46d

test:
  secret_key_base: 97ab325aab866d26ee7492a48d3cbbc34bdac4e8536eaf179d02f34b1570fa9ce28d00c5137d07b6c7734049fe2ee31c60fc9870ca16ee873a77c7e5172f751a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
